name: 'Create a comment'
description: 'Create a pull request comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
    required: true
  repository:
    description: 'name of the repository.'
    default: ${{ github.repository }}
    required: true
  pr-id:
    description: 'id of the pull request.'
    required: true
  text:
    description: 'Comment content'
    required: true
outputs:
  id:
    description: 'id of the created comment'
runs:
  using: 'node16'
  main: 'dist/index.js'
